[project1]
project1_server ansible_host=54.76.164.8 ansible_user=ubuntu ansible_ssh_private_key_file="{{ inventory_dir }}/../terraform/aws-alb-docker.pem"

[project2]
project2_server ansible_host=34.244.14.44 ansible_user=ubuntu ansible_ssh_private_key_file="{{ inventory_dir }}/../terraform/aws-alb-docker.pem"
