[project1]
<<<<<<< HEAD
project1_server ansible_host=3.255.175.92 ansible_user=ubuntu ansible_ssh_private_key_file="{{ inventory_dir }}/../terraform/aws-alb-docker.pem"

[project2]
project2_server ansible_host=3.251.78.24 ansible_user=ubuntu ansible_ssh_private_key_file="{{ inventory_dir }}/../terraform/aws-alb-docker.pem"
=======
project1_server ansible_host=18.203.188.120 ansible_user=ubuntu ansible_ssh_private_key_file="{{ inventory_dir }}/../terraform/aws-alb-docker.pem"

[project2]
project2_server ansible_host=108.129.192.75 ansible_user=ubuntu ansible_ssh_private_key_file="{{ inventory_dir }}/../terraform/aws-alb-docker.pem"
>>>>>>> 85dd8da42bc3c579f0ef8e04df71c02268c32a98
